version: '3'
volumes:
  m2:
    external:
      false
services:
  build-code:
    image:  maven:3.3-jdk-8
    volumes:
    - m2:/root/.m2
    - .:/usr/src
    working_dir: "/usr/src"
    command: "mvn clean package"
  json4img-rest:
    build:
      context: json4img-rest
    image: openjdk:8
    command: --server --local
    ports:
    - "8080:8080"
    volumes:
    - ${IMAGES_DIR}:/usr/images
    environment:
      FS_SHAREDDIR: /usr/images