version: '3'
volumes:
  m2:
    external:
      false
services:
  build-code:
    image:  maven:3.3-jdk-8
    volumes:
    - m2:/root/.m2
    - .:/usr/src
    command: bash -c "cd /usr/src && mvn clean package"
  json4img-rest:
    build:
      context: json4img-rest
    image: openjdk:8
    command: --server --config=classpath:com/github/vitalz/jrest/json4img/server.yml
    ports:
    - 8080:8080